In [2]:
import numpy as np 

In [6]:
# 从 arr 中提取所有的奇数
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [11]:
# 将arr中的所有奇数替换为-1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr%2==1]=-1
arr

# 将arr中的所有奇数替换为-1，而不改变arr
t=arr.copy()
t[t%2==1]=-1
t,np.shares_memory(t,arr)

t1=np.where(arr,arr%2==1,-1) # where会生成新的副本
t1,np.shares_memory(t1,arr)

(array([-1,  1,  0,  1,  0,  1,  0,  1,  0,  1]), False)

In [12]:
# 将一维数组转换为2行的2维数组
arr =np.arange(10)

arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
# 垂直堆叠数组a和数组b
# dim必须相同
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack((a,b)),np.concatenate([a,b],axis=0),np.r_[a,b]

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]))

In [32]:
# 将数组a和数组b水平堆叠
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

np.hstack((a,b))

np.concatenate((a,b),axis=1)

np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [36]:
# > array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
a = np.array([1,2,3])

np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [46]:
# 获取数组a和数组b之间的公共项
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b) #intersect 交集
# np.unique 并集

array([2, 4])

In [47]:
# 从数组a中删除数组b中的所有项
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b) # setdiff1d 差集

array([1, 2, 3, 4])

In [50]:
# 获取a和b元素匹配的位置

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b) # where 返回的下标

(array([1, 3, 5, 7]),)

In [62]:
# 获取5到10之间的所有项目

a = np.array([2, 6, 1, 9, 10, 3, 27])

# 1
a[np.where((a>=5) & (a<=10))]

# 2
a[np.where(np.logical_and(a>=5,a<=10))]

# 3
a[(a>=5) & (a<=10)]


array([ 6,  9, 10])

In [2]:
# 转换适用于两个标量的函数maxx，以处理两个数组
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
''' 
Define a vectorized function which takes a nested sequence of objects or numpy arrays as 
inputs and returns a single numpy array or a tuple of numpy arrays. The vectorized function 
evaluates pyfunc over successive tuples of the input arrays like the python map function, 
except it uses the broadcasting rules of nump
'''   

pair_max = np.vectorize(maxx, otypes=[float])

pair_max(a,b)


array([6., 7., 9., 8., 9., 7., 5.])

In [23]:
# 在数组arr中交换列1和2。
arr = np.arange(9).reshape(3,3)

arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [24]:
# 交换数组arr中的第1和第2行
arr = np.arange(9).reshape(3,3)

arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [27]:
# 反转二维数组arr的行
arr = np.arange(9).reshape(3,3)

arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [28]:
# 反转二维数组arr的列

arr = np.arange(9).reshape(3,3)

arr[...,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [32]:
# 创建一个形状为5x3的二维数组，以包含5到10之间的随机十进制数
np.random.randint(5,10,15).reshape(5,-1)+np.random.random((5,3))

np.random.uniform(5,10,(5,3))

array([[6.49551223, 6.88437036, 9.2429001 ],
       [7.09356481, 6.68276593, 7.31474126],
       [8.5851779 , 7.73493304, 7.62629723],
       [9.91731638, 7.55649556, 7.04716298],
       [6.30662383, 7.81423917, 9.08100919]])

In [33]:
# 只打印或显示numpy数组rand_arr的小数点后3位

rand_arr = np.random.random((5,3))

np.set_printoptions(precision=3)
rand_arr

array([[0.987, 0.605, 0.292],
       [0.183, 0.66 , 0.251],
       [0.607, 0.082, 0.825],
       [0.394, 0.876, 0.797],
       [0.816, 0.415, 0.67 ]])

In [34]:
# 通过e式科学记数法来打印rand_arr
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
# suppress 抑制
np.set_printoptions(suppress=False)

rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [36]:
# 将numpy数组a中打印的项数限制为最多6个元素
np.set_printoptions(threshold=6)
a = np.arange(15)
a

# 打印完整的numpy数组a而不截断


array([ 0,
        1,
        2,
       ...,
       12,
       13,
       14])

In [4]:
# 导入鸢尾属植物数据集，保持文本不变

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# genfromtxt 导入文本
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:2]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa']], dtype=object)

In [46]:
# 从前面问题中导入的一维鸢尾属植物数据集中提取文本列的物种
iris=np.genfromtxt(url,delimiter=',',dtype='object')
iris.ndim
np.squeeze(iris[:,[4]])
[row[4] for row in iris][:2]


[b'Iris-setosa', b'Iris-setosa']

In [55]:
# 通过省略鸢尾属植物数据集种类的文本字段，将一维鸢尾属植物数据集转换为二维数组iris_2d
np.array([row.tolist()[:4] for row in iris],dtype='float')

np.genfromtxt(url,delimiter=',',dtype='float',usecols=[0,1,2,3])

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       ...,
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [58]:
# 求出鸢尾属植物萼片长度的平均值、中位数和标准差(第1列)
d=np.genfromtxt(url,delimiter=',',dtype='float',usecols=[0])
# 平均数(mean)  中位数(median) 标准差(standard deviation)
np.mean(d),np.median(d),np.std(d)

(5.843333333333334, 5.8, 0.8253012917851409)

In [61]:
# 创建一种标准化形式的鸢尾属植物间隔长度，其值正好介于0和1之间，这样最小值为0，最大值为1。
d=np.genfromtxt(url,delimiter=',',dtype='float',usecols=[0])
dmax,dmin=d.max(),d.min()

(d-dmin)/(dmax-dmin)

(d-dmin)/d.ptp()

array([0.222, 0.167, 0.111, ..., 0.611, 0.528, 0.444])

In [ ]:
# 计算sepallength的softmax分数


In [5]:
# 找到鸢尾属植物数据集的第5和第95百分位数
d=np.genfromtxt(url,delimiter=',',usecols=[0],dtype='float')
np.percentile(d,q=[5,95]) # percentile 百分位

array([4.6  , 7.255])

In [26]:
# 在iris_2d数据集中的20个随机位置插入np.nan值
d=np.genfromtxt(url,delimiter=',',dtype='object')
# 不加condi返回mesh grid
# method 1
i,j=np.where(d)
np.random.seed=100
d[np.random.choice(i,20),np.random.choice(j,20)]=np.nan
d[0:20]

# method 2
np.random.seed=100
d[np.random.randint(150,size=20),np.random.randint(4,size=20)]=np.nan


array([b'1.5', b'6.7', b'1.2', b'1.2', b'7.2', b'6.7', b'4.6', b'3.6',
       b'3.5', b'3.1', b'3.0', b'2.8', b'3.4', b'7.3', b'3.2', b'2.9',
       b'0.2', b'2.5', b'6.7', b'4.9'], dtype=object)

In [30]:
# 在iris_2d的sepallength中查找缺失值的数量和位置（第1列）
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

np.where(np.isnan(iris_2d[:,0])),np.isnan(iris_2d[:,0]).sum()

((array([ 48,  55,  84, 110, 120]),), 5)

In [46]:
# 过滤具有petallength（第3列）> 1.5 和 sepallength（第1列）< 5.0 的iris_2d行
iris_2d=np.genfromtxt(url,delimiter=',',dtype='float',usecols=[0,1,2,3])

#
iris_2d[np.where(np.logical_and(iris_2d[:,2]>1.5,iris_2d[:,1]<5.0))]

condition=(iris_2d[:,2]>1.5) & (iris_2d[:,0]<5.0)
iris[condition]

array([[b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.9', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.1', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.9', b'2.4', b'3.3', b'1.0', b'Iris-versicolor'],
       [b'4.9', b'2.5', b'4.5', b'1.7', b'Iris-virginica']], dtype=object)

In [55]:
# 选择没有任何nan值的iris_2d行
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
# method 1
data=[~np.any(np.isnan(row))for row in iris_2d]
iris_2d[data][:5]

# method 2 
iris_2d[np.sum(np.isnan(iris_2d),axis=1)==0][:5]


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [ ]:
#在iris_2d中找出SepalLength（第1列）和PetalLength（第3列）之间的相关性


In [56]:
# 找出iris_2d是否有任何缺失值。
iris_2d=np.genfromtxt(url,delimiter=',',dtype='float',usecols=[0,1,2,3])

np.isnan(iris_2d).any()

False

In [62]:
# 在numpy数组中将所有出现的nan替换为0
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# np.where(np.isnan(iris_2d),iris_2d,0)
iris_2d[np.isnan(iris_2d)]=0


In [63]:
# 找出鸢尾属植物物种中的独特值和独特值的数量
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

data=[row.tolist()[4] for row in iris]
np.unique(data,return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype='|S15'),
 array([50, 50, 50]))

In [66]:
# 将iris_2d的花瓣长度（第3列）加入以形成文本数组，这样如果花瓣长度为
# Less than 3 --> 'small'
# 3-5 --> 'medium'
# >=5 --> 'large'

iris_2d=np.genfromtxt(url,delimiter=',',dtype='float',usecols=[0,1,2,3])
# digitize 转换
data=np.digitize(iris_2d[:,2],[0,3,5,10])
mapping={1:'small',2:'medium',3:'large',4:np.nan}

[mapping[i] for i in data][:5]

['small', 'small', 'small', 'small', 'small']

In [93]:
# 在iris_2d中为卷创建一个新列，其中volume是（pi x petallength x sepal_length ^ 2）/ 3
ris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

data=(np.pi*iris_2d[:,2]*iris_2d[:,0])/3
# dim 必须相同
np.concatenate([iris_2d,data[:,np.newaxis]],axis=1)
np.c_[iris_2d,data[:,np.newaxis]][:5]


array([[5.1       , 3.5       , 1.4       , 0.2       , 7.47699052],
       [4.9       , 3.        , 1.4       , 0.2       , 7.1837752 ],
       [4.7       , 3.2       , 1.3       , 0.2       , 6.39837704],
       [4.6       , 3.1       , 1.5       , 0.2       , 7.2256631 ],
       [5.        , 3.6       , 1.4       , 0.2       , 7.33038286]])

In [95]:
# 随机抽鸢尾属植物的种类，使得刚毛的数量是云芝和维吉尼亚的两倍
iris = np.genfromtxt(url, delimiter=',', dtype='object')
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])

np.random.seed=100

np.random.choice(a,150,p=[0.5,0.25,0.25])[:5]

array(['Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'], dtype='<U15')

In [97]:
# 第二长的物种setosa的值是多少
iris = np.genfromtxt(url, delimiter=',', dtype='object')

setosa=iris[iris[:,4]==b'Iris-setosa',[2]].astype('float')
np.unique(np.sort(setosa))[-2]

1.7

In [100]:
# 根据sepallength列对虹膜数据集进行排序
# argsort 返回排序的索引
iris_2d[iris_2d[:,2].argsort()][:10]

array([[5.1, 3.5, 1. , 0.2],
       [4.9, 3. , 1.1, 0.2],
       [4.7, 3.2, 1.2, 0.2],
       [4.6, 3.1, 1.2, 0.2],
       [5.4, 3.7, 1.3, 0.2],
       [4.9, 3.1, 1.3, 0.1],
       [5. , 3.4, 1.3, 0.2],
       [4.4, 2.9, 1.3, 0.2],
       [5.4, 3.9, 1.3, 0.4],
       [5. , 3.6, 1.3, 0.2]])

In [106]:
#在鸢尾属植物数据集中找到最常见的花瓣长度值（第3列）
val,count=np.unique(iris_2d[:,2],return_counts=True)
val[count.argmax()]

1.5

In [16]:
# 数据集的petalwidth第4列中查找第一次出现的值大于1.0的位置
iris=np.genfromtxt(url,delimiter=',',dtype='object')
# argmin argmax 都是返回的index
np.argwhere(iris[:, 3].astype(float) > 1.0)[0]

array([50])

In [36]:
# 从数组a中，替换所有大于30到30和小于10到10的值
np.random.seed(100)
a = np.random.uniform(1,50, 20)

# clip 回型针
np.clip(a,a_min=10,a_max=30)

# method 2
np.where(a<10,10,np.where(a>30,30,a))

# help(np.where)


array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361])

In [44]:
# 获取给定数组a中前5个最大值的位置
np.random.seed(100)
a = np.random.uniform(1,50, 20)
a.argsort()[:5]

 # a.argpartition(kth=5)
np.partition(a,kth=-5)


array([11.25090398, 14.42961361, 21.80136195,  9.42510962,  1.23122395,
        6.95688692, 11.76517714,  6.31046763,  7.69862289, 14.64009987,
       10.08108276, 27.62684215, 40.77247431, 33.86670515, 29.17957314,
       40.99501269, 41.466785  , 42.39403048, 44.67477576, 48.95256545])

In [53]:
# 按行计算唯一值的计数 ? error
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))

[np.unique(row,return_counts=True)[1] for row in arr]

[array([1, 2, 1, 1, 1, 2, 2]),
 array([2, 1, 3, 1, 1, 1, 1]),
 array([3, 2, 3, 1, 1]),
 array([1, 2, 1, 1, 2, 1, 2]),
 array([2, 2, 2, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 2, 2, 1])]

In [83]:
# 将array_of_arrays转换为扁平线性1d数组

# **给定：**
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)
# array_of_arrays = np.array([arr1, arr2, arr3])
np.append(np.append(arr1,arr2),arr3)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 计算一次性编码(数组中每个唯一值的虚拟二进制变量) 51?
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)

In [ ]:
# 创建按分类变量分组的行号。使用以下来自鸢尾属植物物种的样本作为输入 52?
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))

In [88]:
# 根据给定的分类变量创建组ID。使用以下来自鸢尾属植物物种的样本作为输入 53?
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))


In [90]:
# 为给定的数字数组a创建排名
np.random.seed(10)
a = np.random.randint(20, size=10)
a.argsort().argsort()

array([4, 2, 6, 0, 8, 7, 9, 3, 5, 1])

In [94]:
# 创建与给定数字数组a相同形状的排名数组
np.random.seed(10)
a = np.random.randint(20, size=[2,5])

a.ravel().argsort().argsort().reshape(a.shape)

array([[4, 2, 6, 0, 8],
       [7, 9, 3, 5, 1]])

In [9]:
# 计算给定数组中每行的最大值

np.random.seed(100)
a = np.random.randint(1,10, [5,3])

[row[np.argmax(row)] for row in a]

# method-1
np.amax(a,axis=1)

# method-2
np.apply_along_axis(np.max,axis=1,arr=a)


array([9, 8, 6, 3, 9])

In [10]:
# 为给定的二维numpy数组计算每行的最小值
np.random.seed(100)
a = np.random.randint(1,10, [5,3])

np.amin(a,axis=1)

array([4, 1, 3, 3, 1])

In [29]:
# 在给定的numpy数组中找到重复的条目(第二次出现以后)
# 并将它们标记为True。第一次出现应该是False的

np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)
# > Array: [0 0 3 0 2 4 2 2 2 2]

unique=np.unique(a,return_index=True)[1]

b=np.zeros(a.shape)

b.fill(False)#
b[unique]=True
b


Array:  [0 0 3 0 2 4 2 2 2 2]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([1., 0., 1., 0., 1., 1., 0., 0., 0., 0.])

In [38]:
# 在二维数字数组中查找按分类列分组的数值列的平均值
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

sepalwidth=iris[:,1].astype('float')

species=np.unique(d)

[{spe:np.mean(sepalwidth[iris[:,4]==spe])} for spe in species]

[{b'Iris-setosa': 3.418},
 {b'Iris-versicolor': 2.7700000000000005},
 {b'Iris-virginica': 2.974}]

In [40]:
from io import BytesIO
from PIL import Image
import PIL,requests

URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
response = requests.get(URL)

I=Image.open(BytesIO(response.content))
image=I.resize([150,150])
arr=np.asarray(image)

im=Image.fromarray(np.uint8(arr))
Image.Image.show(im)

In [42]:
# 从一维numpy数组中删除所有NaN值

a=np.array([1,2,3,np.nan,5,6,7,np.nan])

a[~np.isnan(a)]


array([1., 2., 3., 5., 6., 7.])

In [43]:
# 计算两个数组a和数组b之间的欧氏距离
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

np.linalg.norm(a-b)

6.708203932499369

In [58]:
# 找到一个一维数字数组a中的所有峰值。峰顶是两边被较小数值包围的点
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
# 找diff找到差距是否正向,在用diff找到为-2的
double_diff=np.diff(np.sign(np.diff(a)))

np.where(double_diff==-2)[0]+1

double_diff

array([ 0, -2,  2,  0, -2,  2])

In [67]:
# 从2d数组a_2d中减去一维数组b_1D，使得b_1D的每一项从a_2d的相应行中减去
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3]) 

# > [[2 2 2]
# >  [2 2 2]
# >  [2 2 2]]
a_2d-b_1d[:,None] # 让b_1d变成列


array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [75]:
# 找出x中数字1的第5次重复的索引

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
unique=np.unique(x,return_counts=True,return_index=True)
n=5
np.where(x==1)[0][n-1]

8

In [ ]:
# 66 ..