In [2]:
import numpy as np

In [4]:
a1d=np.arange(-7,7+1)
a1d

array([-7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

###  变型

In [6]:
# 变型为行向量 -1指定维度大小
a1d.reshape(1,-1),np.reshape(a1d,(1,-1))

(array([[-7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7]]),
 array([[-7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7]]))

In [7]:
# 变型为列向量
a1d.reshape(-1,1)

array([[-7],
       [-6],
       [-5],
       [-4],
       [-3],
       [-2],
       [-1],
       [ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7]])

In [8]:
# 整型+排列顺序(先列后行)
a1d.reshape((3,-1),order='F')

array([[-7, -4, -1,  2,  5],
       [-6, -3,  0,  3,  6],
       [-5, -2,  1,  4,  7]])

### 视图和副本

In [9]:
# 判断是否共享内存
t=a1d.reshape((5,-1))

np.shares_memory(t,a1d)

True

### 转置

In [11]:
# 转置
a1d.reshape((3,-1)).T

array([[-7, -2,  3],
       [-6, -1,  4],
       [-5,  0,  5],
       [-4,  1,  6],
       [-3,  2,  7]])

In [23]:
t=a1d.reshape((3,-1))
t
np.swapaxes(t,0,1)

array([[-7, -2,  3],
       [-6, -1,  4],
       [-5,  0,  5],
       [-4,  1,  6],
       [-3,  2,  7]])

In [22]:
np.transpose(t)

array([[-7, -2,  3],
       [-6, -1,  4],
       [-5,  0,  5],
       [-4,  1,  6],
       [-3,  2,  7]])

### 扁平化

In [24]:
a3b5=a1d.reshape((3,5))

In [26]:
# ravel返回的是原始数组的视图,而不是其他副本
# 注意flatten函数返回是一个副本
a3b5.ravel(),np.shares_memory(a1d,a3b5.ravel())


(array([-7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7]), True)

In [28]:
a3b5.reshape(-1),a3b5.flatten()

(array([-7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7]),
 array([-7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7]))

In [29]:
# 旋转
np.rot90(a3b5)

array([[-3,  2,  7],
       [-4,  1,  6],
       [-5,  0,  5],
       [-6, -1,  4],
       [-7, -2,  3]])

In [31]:
# 沿着轴翻转
np.flip(a3b5,axis=1)

array([[-3, -4, -5, -6, -7],
       [ 2,  1,  0, -1, -2],
       [ 7,  6,  5,  4,  3]])

### 堆叠

In [32]:
a=np.arange(0,5)

In [33]:
# 沿行堆叠
np.stack((a,a))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [34]:
np.row_stack((a,a))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [35]:
np.vstack((a,a))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [44]:
em=np.empty((0,5)) # 注意数字

for i in range(3):
    row=np.full((1,5),i)
    em=np.vstack([em,row])

em

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.]])

In [45]:
# 沿列堆叠
np.stack((a,a),axis=1)

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [46]:
np.column_stack((a,a))

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [47]:
# 沿水平反向
np.hstack((a,a))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [51]:
# 拼接
a3b3=np.arange(-4,5).reshape((3,3))

b3b1=np.array([[4,0,4]])

b3b1T=b3b1.T

b3b1T,b3b1

(array([[4],
        [0],
        [4]]),
 array([[4, 0, 4]]))

In [52]:
# 行拼接 维度必须相同
np.concatenate((a3b3,b3b1),axis=0)

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4],
       [ 4,  0,  4]])

In [53]:
# 列拼接
np.concatenate((a3b3,b3b1T),axis=1)

array([[-4, -3, -2,  4],
       [-1,  0,  1,  0],
       [ 2,  3,  4,  4]])

In [54]:
# 列拼接
np.hstack((a3b3,b3b1T))

array([[-4, -3, -2,  4],
       [-1,  0,  1,  0],
       [ 2,  3,  4,  4]])

### 重复

In [57]:
a1d=np.array([1,2,3])

In [58]:
# repeat 重复
np.repeat(a1d,2)

array([1, 1, 2, 2, 3, 3])

In [ ]:
# 瓷砖tile

In [59]:
np.tile(a1d,2)

array([1, 2, 3, 1, 2, 3])

### 分块矩阵

In [61]:
# block组合矩阵
e3=np.eye(2)
a2b2=np.full((2,2),-1)
np.block([e3,a2b2])

array([[ 1.,  0., -1., -1.],
       [ 0.,  1., -1., -1.]])

In [63]:
# split切割
sp1=np.arange(-9,9)

np.split(sp1,3)

[array([-9, -8, -7, -6, -5, -4]),
 array([-3, -2, -1,  0,  1,  2]),
 array([3, 4, 5, 6, 7, 8])]

In [64]:
# 指定index切割
np.split(sp1,[3,4,5])

# 水平方向切割hsplit 
# 竖直方向切割vsplit

[array([-9, -8, -7]),
 array([-6]),
 array([-5]),
 array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])]

### 插入,删除

In [65]:
np.append([1,2],[3,4])

array([1, 2, 3, 4])

In [75]:
np.append([[1,2]],[[3,4]],axis=0) # 注意维度数

array([[1, 2],
       [3, 4]])

In [79]:
a = np.array([[1, 1], [2, 2], [3, 3]])
np.insert(a, [1], [[1],[2],[3]], axis=1)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [81]:
np.insert(a,1,2,axis=1) #1指插入那个元素之前

array([[1, 2, 1],
       [2, 2, 2],
       [3, 2, 3]])

In [83]:
np.delete(a,1,axis=1)

array([[1],
       [2],
       [3]])