In [2]:
import numpy as np

### 整形

In [4]:
# 特殊索引np.newaxis,用于增加数组维度;squeeze删除维度简化形状
a=np.linspace(-5,5,11)

a[np.newaxis,:]
# a[:,np.newaxis]

a.squeeze()

b=np.array([[[1,2],[3,4],[5,6]]])
np.squeeze(b),b[np.newaxis,:],b[...,np.newaxis]

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[[[1, 2],
          [3, 4],
          [5, 6]]]]),
 array([[[[1],
          [2]],
 
         [[3],
          [4]],
 
         [[5],
          [6]]]]))

In [35]:
# reshape调整形态 -1表示根据上下文估算
a.reshape(1,-1)
a.reshape(-1,1)

array([[-5.],
       [-4.],
       [-3.],
       [-2.],
       [-1.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.]])

In [37]:
# 使用None调整
a[:,None]
a[None,:]

array([[-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.]])

### 索引和切片

In [33]:
# 索引和切片
a=np.linspace(-5,5,11)

# 嵌套数组取对应下标
a[[0,1,2,-1]]



array([-5., -4., -3.,  5.])

In [40]:
# 取奇偶下标
a[1::2],a[0::2]

(array([-4., -2.,  0.,  2.,  4.]), array([-5., -3., -1.,  1.,  3.,  5.]))

In [38]:
# bool索引
a[a>0]

array([1., 2., 3., 4., 5.])

In [73]:
# 索引
# np.r_用于将切片对象转换为沿着第一个轴叠加的数组
np.r_[0:3,-1]
# concatenate和vstack效果相同
a[np.r_[0:3,-1]],np.concatenate((a[0:3],a[-1:])),np.vstack((a[0:3],a[-3:]))

(array([-5., -4., -3.,  5.]),
 array([-5., -4., -3.,  5.]),
 array([[-5., -4., -3.],
        [ 3.,  4.,  5.]]))

### 视图和副本

In [5]:
# 视图和副本
# copy函数生成副本
# 可以用may_share_memory来判断是否共享内存
a=np.linspace(-5,5,11)
b=np.vstack((a[:],a[:]))

np.may_share_memory(a,a[:]),b

(True,
 array([[-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.],
        [-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.]]))

### 二维索引和切片

In [ ]:
# 二维数组索引和切片

In [83]:
a2d = np.array([[-7,-6,-5,-4,-3],
                 [-2,-1, 0, 1, 2],
                 [ 3, 4, 5, 6, 7]])

In [86]:
# 取一个元素
a2d[0][0],a2d[0,0]

(-7, -7)

In [87]:
# 取一个元素,返回数组
a2d[[0],[0]] # 嵌套数组取的

array([-7])

In [89]:
# 取列
a2d[:,0]

array([-7, -2,  3])

In [88]:
# 取行
a2d[0]

array([-7, -6, -5, -4, -3])

In [92]:
# 取出第一行,结果为二维数组
a2d[[0],:],a2d[0,np.newaxis]

(array([[-7, -6, -5, -4, -3]]), array([[-7, -6, -5, -4, -3]]))

In [115]:
# np.ix_
a2d[np.ix_([0,2],[0,2])] # 取0,2行 再取0,2列
a2d[[0,2],:][:,0:2] # 先去2行得到一个子矩阵,在从这个矩阵里继续取

array([[-7, -6],
       [ 3,  4]])

更多有关NumPy索引和切片，请参考：  
https://numpy.org/doc/stable/user/how-to-index.html  
https://numpy.org/doc/stable/user/basics.indexing.html
https://www.numpy.org.cn/article/advanced/numpy_exercises_for_data_analysis.html
